### ISSUE TITLE
Yolov5m6 tensorrt onnx error

### ISSUE THREAD

**Issue by phoenixGG** [wep21/aws_sdk_cpp_vendor#1]
Hi, I'm sorry to bother you, I don't know your email so I'm contacting you this way. I am interested in autoware tensorrt_yolo.I converted yolov5m6 to tensorrt onnx model, but the autoware program reported an error after starting it, does the current version of AUTOWARE not support Yolov5m6 model (size: 1280)?
![99](https://github.com/wep21/aws_sdk_cpp_vendor/assets/8891789/e9e039ca-ff23-4964-9432-eafb36f4ec74)

**Comment by wep21** [comment]
I will reply on email.

**Comment by phoenixGG** [comment]
OK，my email is cccmore1030@gmail.com

**Comment by phoenixGG** [comment]
> I will reply on email.

OK, my email is cccmore1030@gmail.com

**Comment by phoenixGG** [comment]
> I will reply on email.

OK, my email is cccmore1030@gmail.com, @wep21
